### ISSUE TITLE
Latest beta - can't accept/decline meeting invites

### ISSUE THREAD

**Issue by tfft** [Ericsson/exchangecalendar#224]
Hi, I'm unable to accept/decline new meeting notifications with the latest beta release (3.4.0-beta2).  I see the following errors/warnings in the "Error Console".  Do note that I'm using TB's latest release (38.0.1).  This, obviously, was working before...

Timestamp: 2015-06-14 1:33:20 PM
Error: NS_ERROR_XPC_NEED_OUT_OBJECT: 'Out' argument must be an object arg 1 [nsIMsgCustomColumnHandler.getRowProperties]
Source File: chrome://exchangecalendar/content/priority-display.js
Line: 178

Timestamp: 2015-06-14 1:33:20 PM
Warning: This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.
Source File: https://[hidden-hideen]/EWS/Exchange.asmx
Line: 0

-----  Another related topic -----
I also just noticed that I have a "Invitations: 4" on the status bar (bottom right), clicking that gives me the first error above (NS_ERROR_XPC_NEED_OUT_OBJECT) and the following warnings in the console,  Upon clicking, I get a window (which used to list the pending meetings) which now doesn't list anything and simply notes "Updating list of invitations." with an ever circling prompt.

Timestamp: 2015-06-14 3:16:27 PM
Warning: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
Source File: chrome://calendar/content/calUtils.js
Line: 1190, Column: 21
Source Code:
            function eq(obj) { 

Timestamp: 2015-06-14 3:16:27 PM
Warning: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
Source File: chrome://calendar/content/calUtils.js
Line: 1204, Column: 21
Source Code:
            function neq(obj) { 

Timestamp: 2015-06-14 3:16:27 PM
Warning: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
Source File: chrome://calendar/content/calUtils.js
Line: 1290, Column: 21
Source Code:
            function filterFunc(op_) { 

Timestamp: 2015-06-14 3:16:27 PM
Warning: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
Source File: chrome://calendar/content/calUtils.js
Line: 1341, Column: 21
Source Code:
            function forEachFunc(op) {

**Comment by bavincen** [comment]
seems strict mode issue.. we are not completed wth this issue.. please tell us ur lightning version, also any strict mode error

**Comment by tfft** [comment]
As noted I'm using the latest release TB which ships with lightning 4.0.0.1 -- am I supposed to have "strict mode" disabled ?  If so, how do I do that ?  Won't other users be affected and see the same issue(s).  Please note that I didn't change any of my settings and EWS-3.3.2 was/is working fine (strict mode or otherwise).

The only error I see in the Error Console is the one cited above regarding 'NS_ERROR_XPC_NEED_OUT_OBJECT'.

Thanks.

**Comment by bavincen** [comment]
javascript.options.strict  set to false.. let me know if this works for you.. we will resolve this

**Comment by tfft** [comment]
No, that doesn't seem to have helped in any way - I'm still unable to accept/decline meetings, etc.  The error noted continues to show-up on the error console.

**Comment by bavincen** [comment]
Ok please post error log.. U can mail us

**Comment by tfft** [comment]
The errors were noted in the first message in this thread.

**Comment by troyengel** [comment]
I am also having this issue -- 3.4.0-b1/b2 caused:

- no meetings to accept/decline using the top level button on the Invite
- no meetings showing up in the status bar as Invites (which brings up that alternate dialog to accept, usually)
- attempting to Dismiss any snooze dialogs just fails - I have to [X] them and they keep popping up

I was noticing a bunch of other squirrely behaviour as well - some meetings would not sync down from Exchange, some deletions would not sync upstream and things of that nature. I downgraded to 3.3.2 and it's all working as expected -- I'm afraid I don't have time right now to turn on debug logs and test the betas further, but I can try later if needed. They seem quite broken compared to 3.3.2 release.

    Distro: Arch 64bit
    Thunderbird: 38.0.1
    Lightning: 4.0.0.1
    Enigmail 1.8.2 and .vcs Support 0.6.4 are my only other two Add-ons

Here's what the Exchange Properties dialog reports:

    Exchange Server Version: V2_22 (15.0.1044.21)  <- Exchange 2012 I think

I have Caching turned on in the properties as well, seems to be working OK.

**Comment by muthusuba** [comment]
me too...

**Comment by bavincen** [comment]
file:///home/ebabvin/.thunderbird/user.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/exchangeCalendar/mivExchangeCalendar.js, line 2932: reference to undefined property aItem.myResponseType

What  i can see in error..

The modified item/cloned item sent from imip toolbar with null value( myResponseType ) is issue

**Comment by IamLosted** [comment]
I am having this issue too with the latest 3.4.0 b1/b2

**Comment by awilkins** [comment]
Likewise, can't accept meeting invites

The "Accept" button shows, clicking it just leaves some detritus in the UI, doesn't show the dialog box for mailing a response. When you move away from the invite and focus returns the Accept / Tentative / Decline buttons return like nothing happened.

![event-accept-decline](https://cloud.githubusercontent.com/assets/368399/8182685/c540e0cc-1429-11e5-9c1f-79583af96aeb.png)

You can see a dark box on the right like some of the buttons were left behind

![event-accepted-event-loop-stalled](https://cloud.githubusercontent.com/assets/368399/8182689/c8e6b3d2-1429-11e5-9e0b-e460bce675ac.png)

Maybe the click event loop has been broken by an exception, but there is nothing in the error console.

Turned on a bunch of logging... aside from these

    1st-setup:2015-5-2 13:12:38.787:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({e46d924d-c20f-4add-8cf5-1e1c817b2181})
    1st-setup:2015-5-2 13:12:38.787:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({2b6d6fb6-ab28-4f4c-af84-bfdbb7866d72})

I can't see anything anomalous but it is quite a verbose log.

**Comment by bartlibert** [comment]
I also have this issue, but I see a different error in the logs, so I don't know for sure if this is related or if I should create a new issue.

6dece682-36b3-4741-9437-76e3d719fefd:https://<removed for privacy>/EWS/Exchange.asmx:jobObject.onRequestOk Error:TypeError: this._messageId is undefined

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

FIXED

**Comment by tfft** [comment]
It might be worth while to explain what the problem was and what solution was enacted to fix the issue.  I'm just thinking that such explanations would at a minimum give curious potential contributors/developers something to go look into the code for and potentially help out in the future...

Just a thought.

**Comment by bavincen** [comment]
i will keep referencing commit messages 
thanks @tfft

**Comment by tfft** [comment]
I just tried a "master" snapshot and that didn't improve anything - the original bug/problem report is still there for me at least (don't know about others).  In passing, I'm still seeing lots of those "NS_ERROR_XPC_NEED_OUT_OBJECT" errors in the console.

**Comment by bavincen** [comment]
if you are using 4.0 lightning, support is enabled now.. please confirm .. thanks

**Comment by tfft** [comment]
You are correct - my bad (apologies).  You are now able to accept/decline meetings.  The error message, though, is still there in the console (not sure its related or not).
